import React, { useState } from 'react';
import { 
  Copy, 
  Check, 
  RotateCw, 
  ThumbsUp, 
  ThumbsDown, 
  Edit3, 
  Volume2, 
  VolumeX, 
  FileText, 
  Image as ImageIcon, 
  Globe,
  ExternalLink,
  ChevronDown,
  ChevronRight,
  Brain
} from 'lucide-react';
import type { Message, AttachedFile, CitationItem } from '../../types';
import { MarkdownRenderer } from '../common/MarkdownRenderer';
import { useAppStore } from '../../store/appStore';

interface MessageItemProps {
  message: Message;
  isLastAssistant?: boolean;
}

export const MessageItem: React.FC<MessageItemProps> = ({ message, isLastAssistant }) => {
  const { 
    submitFeedback, 
    sendMessage, 
    regenerateResponse 
  } = useAppStore();

  const [copied, setCopied] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState(message.content);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [showThought, setShowThought] = useState(false);

  const isUser = message.role === 'user';

  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSpeak = () => {
    if (!('speechSynthesis' in window)) return;
    
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    window.speechSynthesis.cancel();
    const clean = message.content.replace(/[#*`$_\-\[\]]/g, ' ');
    const utterance = new SpeechSynthesisUtterance(clean);
    utterance.rate = 1.0;
    
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  };

  const handleSaveEdit = () => {
    if (!editContent.trim()) return;
    setIsEditing(false);
    sendMessage(editContent.trim(), message.attachments, []);
  };

  // Parse `<think>` tags if generated by reasoning models
  let displayContent = message.content;
  let extractedThought = message.thought || '';
  if (message.content.includes('<think>') && message.content.includes('</think>')) {
    const parts = message.content.split('</think>');
    extractedThought = parts[0].replace('<think>', '').trim();
    displayContent = parts.slice(1).join('</think>').trim();
  }

  return (
    <div className={`py-4 px-4 sm:px-6 md:px-8 transition-colors ${
      isUser ? 'flex justify-end' : 'bg-transparent'
    }`}>
      <div className={`max-w-3xl w-full mx-auto ${isUser ? 'flex justify-end' : ''}`}>
        {isUser ? (
          /* User Message: Clean Gray Rounded Pill on the Right (Exact ChatGPT Parity) */
          <div className="group relative max-w-[85%] sm:max-w-[75%] space-y-1.5">
            {/* Attached Files Preview */}
            {message.attachments && message.attachments.length > 0 && (
              <div className="flex flex-wrap gap-1.5 justify-end pb-1">
                {message.attachments.map((file, fIdx) => (
                  <div
                    key={fIdx}
                    className="flex items-center gap-1.5 px-2.5 py-1 rounded-xl bg-[var(--bg-input)] border border-[var(--border-subtle)] text-xs text-[var(--text-primary)]"
                  >
                    {file.isImage ? (
                      <ImageIcon className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                    ) : (
                      <FileText className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
                    )}
                    <span className="max-w-[120px] truncate">{file.filename}</span>
                  </div>
                ))}
              </div>
            )}

            {/* Bubble Pill or Edit Mode */}
            {isEditing ? (
              <div className="space-y-2 bg-[var(--bg-input)] p-3 rounded-2xl border border-[var(--border-medium)]">
                <textarea
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  className="w-full bg-transparent text-[var(--text-primary)] text-sm focus:outline-none min-h-[70px] resize-y"
                />
                <div className="flex items-center gap-2 justify-end">
                  <button
                    onClick={() => setIsEditing(false)}
                    className="px-2.5 py-1 rounded-lg bg-[var(--bg-surface)] hover:bg-[var(--bg-surface-hover)] text-xs font-medium text-[var(--text-primary)] cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleSaveEdit}
                    className="px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium cursor-pointer"
                  >
                    Save & Submit
                  </button>
                </div>
              </div>
            ) : (
              <div className="inline-block bg-[var(--bg-sidebar-hover)] hover:bg-[var(--border-input)] transition px-4 py-2.5 rounded-3xl text-[var(--text-primary)] text-[14.5px] leading-relaxed shadow-sm break-words whitespace-pre-wrap">
                {displayContent}
              </div>
            )}

            {/* Hover Actions for User */}
            <div className="flex items-center gap-1 justify-end opacity-0 group-hover:opacity-100 transition-opacity text-xs text-[var(--text-muted)]">
              <button
                onClick={handleCopy}
                className="p-1 rounded hover:bg-[var(--bg-sidebar-hover)] transition cursor-pointer"
                title="Copy message"
              >
                {copied ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3" />}
              </button>
              <button
                onClick={() => setIsEditing(!isEditing)}
                className="p-1 rounded hover:bg-[var(--bg-sidebar-hover)] transition cursor-pointer"
                title="Edit message"
              >
                <Edit3 className="w-3 h-3" />
              </button>
            </div>
          </div>
        ) : (
          /* Assistant Message: Left-aligned with Clean Typography, Citations, & Thought Dropdown */
          <div className="group space-y-2.5">
            {/* Model Badge */}
            {message.model && (
              <div className="flex items-center gap-2 text-[11px] font-medium text-[var(--text-muted)]">
                <span>{message.model}</span>
              </div>
            )}

            {/* Live Web Search Citation Cards */}
            {message.citations && message.citations.length > 0 && (
              <div className="p-2.5 rounded-2xl bg-[var(--bg-sidebar)] border border-[var(--border-subtle)] space-y-2 max-w-xl">
                <div className="flex items-center gap-1.5 text-xs font-semibold text-blue-400">
                  <Globe className="w-3.5 h-3.5" />
                  <span>Searched the web ({message.citations.length} sources)</span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {message.citations.map((cite, cIdx) => (
                    <a
                      key={cIdx}
                      href={cite.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1.5 px-2.5 py-1 rounded-xl bg-[var(--bg-main)] hover:bg-[var(--bg-sidebar-hover)] border border-[var(--border-subtle)] text-[11px] text-[var(--text-primary)] transition group/link max-w-[200px]"
                      title={cite.snippet || cite.title}
                    >
                      {cite.favicon ? (
                        <img src={cite.favicon} alt="" className="w-3.5 h-3.5 rounded-sm shrink-0" onError={(e) => (e.currentTarget.style.display = 'none')} />
                      ) : (
                        <Globe className="w-3.5 h-3.5 text-[var(--text-muted)] shrink-0" />
                      )}
                      <span className="truncate">{cite.domain || cite.title}</span>
                      <ExternalLink className="w-2.5 h-2.5 text-[var(--text-muted)] group-hover/link:text-[var(--text-primary)] shrink-0" />
                    </a>
                  ))}
                </div>
              </div>
            )}

            {/* Collapsible Reasoning Thought Accordion (Exact ChatGPT / DeepSeek Style) */}
            {extractedThought && (
              <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-sidebar-hover)] overflow-hidden">
                <button
                  onClick={() => setShowThought(!showThought)}
                  className="w-full flex items-center justify-between px-3 py-2 text-xs font-medium text-[var(--text-muted)] hover:text-[var(--text-primary)] transition cursor-pointer"
                >
                  <div className="flex items-center gap-2">
                    <Brain className="w-3.5 h-3.5 text-purple-400" />
                    <span>{showThought ? 'Thinking Process' : 'Thought for a few seconds'}</span>
                  </div>
                  {showThought ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronRight className="w-3.5 h-3.5" />}
                </button>
                {showThought && (
                  <div className="p-3 text-xs text-[var(--text-secondary)] border-t border-[var(--border-subtle)] font-mono whitespace-pre-wrap leading-relaxed bg-[var(--bg-main)]/50">
                    {extractedThought}
                  </div>
                )}
              </div>
            )}

            {/* Main Assistant Content */}
            <div className="text-[var(--text-primary)] text-[15px] leading-relaxed break-words">
              <MarkdownRenderer content={displayContent} />
            </div>

            {/* Bottom Action Bar for Assistant */}
            <div className="flex items-center gap-1 pt-1 text-xs text-[var(--text-muted)] opacity-80 group-hover:opacity-100 transition-opacity">
              <button
                onClick={handleCopy}
                className="p-1.5 rounded-lg hover:bg-[var(--bg-sidebar-hover)] hover:text-[var(--text-primary)] transition cursor-pointer"
                title="Copy response"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              </button>

              <button
                onClick={handleSpeak}
                className={`p-1.5 rounded-lg hover:bg-[var(--bg-sidebar-hover)] hover:text-[var(--text-primary)] transition cursor-pointer ${
                  isSpeaking ? 'text-emerald-500' : ''
                }`}
                title={isSpeaking ? 'Stop speech' : 'Read aloud'}
              >
                {isSpeaking ? <VolumeX className="w-3.5 h-3.5 text-emerald-500" /> : <Volume2 className="w-3.5 h-3.5" />}
              </button>

              {isLastAssistant && (
                <button
                  onClick={regenerateResponse}
                  className="p-1.5 rounded-lg hover:bg-[var(--bg-sidebar-hover)] hover:text-[var(--text-primary)] transition cursor-pointer"
                  title="Regenerate response"
                >
                  <RotateCw className="w-3.5 h-3.5" />
                </button>
              )}

              <button
                onClick={() => submitFeedback(message.id, 'like')}
                className={`p-1.5 rounded-lg hover:bg-[var(--bg-sidebar-hover)] transition cursor-pointer ${
                  message.feedback === 'like' ? 'text-emerald-500' : 'hover:text-[var(--text-primary)]'
                }`}
                title="Good response"
              >
                <ThumbsUp className="w-3.5 h-3.5" />
              </button>

              <button
                onClick={() => submitFeedback(message.id, 'dislike')}
                className={`p-1.5 rounded-lg hover:bg-[var(--bg-sidebar-hover)] transition cursor-pointer ${
                  message.feedback === 'dislike' ? 'text-rose-500' : 'hover:text-[var(--text-primary)]'
                }`}
                title="Bad response"
              >
                <ThumbsDown className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
